# Generated by Django 4.1 on 2024-07-03 13:11

from django.db import migrations
import django_quill.fields


class Migration(migrations.Migration):

    dependencies = [
        ('blog_post', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog_post',
            name='blog_post',
            field=django_quill.fields.QuillField(),
        ),
    ]
