# Generated by Django 4.1 on 2024-07-03 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_post', '0002_alter_blog_post_blog_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog_post',
            name='post_image',
            field=models.ImageField(null=True, upload_to='post_images'),
        ),
    ]
