# Generated by Django 4.1 on 2024-07-06 02:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_post', '0005_image_upload'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blog_post',
            options={'permissions': [('publish_post', 'Can publish post'), ('feature_post', 'Can feature post')]},
        ),
        migrations.AlterField(
            model_name='image_upload',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
