# Generated by Django 4.1 on 2024-07-06 04:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_post', '0006_alter_blog_post_options_alter_image_upload_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog_post',
            name='post_image',
            field=models.ImageField(null=True, upload_to='images/'),
        ),
    ]
